Pin `libcst==1.2.0` in type checking
After upgrade to `libcst==1.3.0`, running PyType fails with the
following error:

    Traceback (most recent call last):
      File "/usr/local/bin/pytype", line 5, in <module>
        from pytype.tools.analyze_project.main import main
      File "/usr/local/lib/python3.10/site-packages/pytype/tools/analyze_project/main.py", line 11, in <module>
        from pytype import io
      File "/usr/local/lib/python3.10/site-packages/pytype/io.py", line 12, in <module>
        import libcst
      File "/usr/local/lib/python3.10/site-packages/libcst/__init__.py", line 227, in <module>
        from libcst.metadata.base_provider import (
      File "/usr/local/lib/python3.10/site-packages/libcst/metadata/__init__.py", line 53, in <module>
        from libcst.metadata.type_inference_provider import TypeInferenceProvider
      File "/usr/local/lib/python3.10/site-packages/libcst/metadata/type_inference_provider.py", line 11, in <module>
        from mypy_extensions import TypedDict
    ModuleNotFoundError: No module named 'mypy_extensions'

See also
<https://github.com/Witiko/markdown/actions/runs/8545104695/job/23412656377?pr=431>.